<?php

namespace App\Service;

use App\Entity\Domain;
use App\Entity\DnsServer;
use App\Entity\DnsView;
use App\Entity\NetworkInterface;
use App\Entity\Subnet;
use App\Enum\RecordType;
use App\Repository\DnsAclRepository;
use App\Repository\DnssecPolicyRepository;
use App\Repository\DomainRepository;
use App\Repository\SubnetRepository;

class DnsConfigGenerator
{
    public function __construct(
        private readonly DomainRepository       $domainRepo,
        private readonly SubnetRepository       $subnetRepo,
        private readonly DnssecPolicyRepository $policyRepo,
        private readonly DnsAclRepository       $aclRepo,
    ) {}

    /** @return Domain[] */
    public function domainsForView(DnsView $view): array
    {
        return $this->domainRepo->createQueryBuilder('d')
            ->join('d.views', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $view->getId())
            ->orderBy('d.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /** @return Subnet[] */
    public function subnetsForView(DnsView $view): array
    {
        return $this->subnetRepo->createQueryBuilder('s')
            ->join('s.views', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $view->getId())
            ->orderBy('s.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Generates a BIND forward zone file for a domain, filtered to a specific view.
     * Pass null to include all records regardless of view.
     */
    public function generateZoneFile(Domain $domain, ?DnsView $view = null): string
    {
        $defaultTtl = $domain->getSoaTtl() ?? 3600;
        $serial     = time();
        $nameserver = $this->ensureTrailingDot($domain->getSoaNameserver() ?? ('ns1.' . $domain->getName() . '.'));
        $email      = $this->emailToRname($domain->getSoaEmail() ?? ('hostmaster.' . $domain->getName() . '.'));
        $refresh    = $domain->getSoaRefresh() ?? 3600;
        $retry      = $domain->getSoaRetry()   ?? 900;
        $expire     = $domain->getSoaExpire()  ?? 604800;

        $lines   = [];
        $lines[] = '; Zone file for ' . $domain->getName() . ($view ? ' (view: ' . $view->getName() . ')' : '');
        $lines[] = '; Generated by DashDDI at ' . date('Y-m-d H:i:s T');
        $lines[] = '';
        $lines[] = '$ORIGIN ' . rtrim($domain->getName(), '.') . '.';
        $lines[] = '$TTL ' . $defaultTtl;
        $lines[] = '';
        $lines[] = sprintf(
            "@ IN SOA %s %s (\n    %-12s ; serial\n    %-12s ; refresh\n    %-12s ; retry\n    %-12s ; expire\n    %-12s ; minimum TTL\n)",
            $nameserver, $email, $serial, $refresh, $retry, $expire, $defaultTtl
        );
        $lines[] = '';
        $lines[] = sprintf('@ IN NS %s', $nameserver);
        $lines[] = '';

        // All DNS records (manual and interface-linked)
        $recordLines = [];
        foreach ($domain->getRecords() as $record) {
            if (!$this->inView($view, $record->getViews()->toArray())) {
                continue;
            }
            $ttl = $record->getTtl() ? (' ' . $record->getTtl()) : '';
            $iface = $record->getNetworkInterface();
            if ($iface !== null) {
                if ($iface->isDeleted()) {
                    continue;
                }
                // Derive value from interface IP for A/AAAA records
                if ($record->getType() === RecordType::A) {
                    $ip = $iface->getIpAddress();
                    if (!$ip) {
                        continue;
                    }
                    $recordLines[] = sprintf('%s%s IN A %s', $record->getHostname(), $ttl, $ip->getAddress());
                } elseif ($record->getType() === RecordType::AAAA) {
                    $ip = $iface->getIpv6Address();
                    if (!$ip) {
                        continue;
                    }
                    $recordLines[] = sprintf('%s%s IN AAAA %s', $record->getHostname(), $ttl, $ip->getAddress());
                } else {
                    // Other types (TXT, HTTPS, etc.) linked to an interface use the stored value
                    $recordLines[] = sprintf('%s%s IN %s %s', $record->getHostname(), $ttl, $record->getType()->value, $record->getValue());
                }
            } else {
                $recordLines[] = sprintf('%s%s IN %s %s', $record->getHostname(), $ttl, $record->getType()->value, $record->getValue());
            }
        }
        if (!empty($recordLines)) {
            array_push($lines, ...$recordLines);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Generates a BIND reverse zone file for a subnet CIDR (IPv4 or IPv6).
     * PTR records are derived from interface DNS names filtered to the given view.
     */
    public function generateReverseZoneFile(Subnet $subnet, string $cidr, ?DnsView $view = null): string
    {
        [$address, $prefixStr] = explode('/', $cidr);
        $prefix  = (int)$prefixStr;
        $isIpv6  = str_contains($address, ':');
        $zoneName = $this->reverseZoneName($cidr);

        $nameserver = $this->ensureTrailingDot($subnet->getSoaNameserver() ?? $this->defaultNs($view));
        $email      = $this->emailToRname($subnet->getSoaEmail() ?? $this->defaultEmail($view, false));
        $defaultTtl = $subnet->getSoaTtl()    ?? 3600;
        $refresh    = $subnet->getSoaRefresh() ?? 3600;
        $retry      = $subnet->getSoaRetry()   ?? 900;
        $expire     = $subnet->getSoaExpire()  ?? 604800;
        $serial     = time();

        $lines   = [];
        $lines[] = '; Reverse zone for ' . $cidr . ($view ? ' (view: ' . $view->getName() . ')' : '');
        $lines[] = '; Generated by DashDDI at ' . date('Y-m-d H:i:s T');
        $lines[] = '';
        $lines[] = '$ORIGIN ' . $zoneName . '.';
        $lines[] = '$TTL ' . $defaultTtl;
        $lines[] = '';
        $lines[] = sprintf(
            "@ IN SOA %s %s (\n    %-12s ; serial\n    %-12s ; refresh\n    %-12s ; retry\n    %-12s ; expire\n    %-12s ; minimum TTL\n)",
            $nameserver, $email, $serial, $refresh, $retry, $expire, $defaultTtl
        );
        $lines[] = '';
        $lines[] = sprintf('@ IN NS %s', $nameserver);
        $lines[] = '';

        $ptrLines = [];
        foreach ($subnet->getInterfaces() as $iface) {
            if ($iface->isDeleted()) {
                continue;
            }
            $ip = $isIpv6 ? $iface->getIpv6Address() : $iface->getIpAddress();
            if (!$ip) {
                continue;
            }

            $hostname = $this->ptrHostname($iface, $view, $isIpv6);
            if (!$hostname) {
                continue;
            }

            $label      = $isIpv6
                ? $this->ipv6PtrLabel($ip->getAddress(), $prefix)
                : $this->ipv4PtrLabel($ip->getAddress(), $prefix);
            $ptrLines[] = sprintf('%s IN PTR %s', $label, $hostname);
        }

        if (!empty($ptrLines)) {
            array_push($lines, ...$ptrLines);
            $lines[] = '';
        }

        // Manual records
        $recordLines = [];
        foreach ($subnet->getRecords() as $record) {
            if (!$this->inView($view, $record->getViews()->toArray())) {
                continue;
            }
            $ttl           = $record->getTtl() ? (' ' . $record->getTtl()) : '';
            $recordLines[] = sprintf('%s%s IN %s %s', $record->getHostname(), $ttl, $record->getType()->value, $record->getValue());
        }
        if (!empty($recordLines)) {
            $lines[] = '; Manual records';
            array_push($lines, ...$recordLines);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Generates a dashddi.conf BIND include file listing all forward and reverse zones.
     */
    public function generateViewsConf(DnsServer $server): string
    {
        $zonePath = rtrim($server->getRemoteZonePath(), '/');

        $lines   = [];
        $lines[] = '// BIND views configuration — generated by DashDDI at ' . date('Y-m-d H:i:s T');
        $lines[] = '// Include in named.conf:  include "' . $zonePath . '/dashddi.conf";';
        $lines[] = '';

        foreach ($this->aclRepo->findBy([], ['name' => 'ASC']) as $acl) {
            $lines[] = 'acl "' . $acl->getName() . '" {';
            foreach ($acl->getEntries() as $entry) {
                $lines[] = '    ' . $entry . ';';
            }
            $lines[] = '};';
            $lines[] = '';
        }

        foreach ($this->policyRepo->findBy([], ['name' => 'ASC']) as $policy) {
            $lines[] = 'dnssec-policy "' . $policy->getName() . '" {';
            foreach ([
                'dnskey-ttl'          => $policy->getDnskeyTtl(),
                'max-zone-ttl'        => $policy->getMaxZoneTtl(),
                'signatures-validity' => $policy->getSignaturesValidity(),
                'signatures-refresh'  => $policy->getSignaturesRefresh(),
                'publish-safety'      => $policy->getPublishSafety(),
                'retire-safety'       => $policy->getRetireSafety(),
                'purge-keys'          => $policy->getPurgeKeys(),
            ] as $directive => $value) {
                if ($value !== null) {
                    $lines[] = '    ' . $directive . ' ' . $value . ';';
                }
            }
            if ($policy->getNsec3param() !== null) {
                $lines[] = '    nsec3param ' . $policy->getNsec3param() . ';';
            }
            $keys = $policy->getKeys();
            if (!empty($keys)) {
                $lines[] = '    keys {';
                foreach ($keys as $key) {
                    $lines[] = '        ' . $key['type'] . ' lifetime ' . $key['lifetime'] . ' algorithm ' . $key['algorithm'] . ';';
                }
                $lines[] = '    };';
            }
            if ($policy->getExtraOptions()) {
                foreach (explode("\n", rtrim($policy->getExtraOptions())) as $optLine) {
                    $lines[] = '    ' . $optLine;
                }
            }
            $lines[] = '};';
            $lines[] = '';
        }

        // Emit a TSIG key block if this server has DDNS configured.
        if ($server->getDdnsAlgorithm() && $server->getDdnsSecret()) {
            $lines[] = 'key "' . $server->getDdnsKeyName() . '" {';
            $lines[] = '    algorithm ' . $server->getDdnsAlgorithm()->bindName() . ';';
            $lines[] = '    secret "' . $server->getDdnsSecret() . '";';
            $lines[] = '};';
            $lines[] = '';
        }

        foreach ($server->getViews() as $view) {
            $domains = $this->domainsForView($view);
            $subnets = $this->subnetsForView($view);

            $lines[] = 'view "' . $view->getName() . '" {';

            $matchClients = $view->getMatchClients();
            if (!empty($matchClients)) {
                $loopback = $view->getNsUpdateSourceAddress();
                if ($loopback !== null && !in_array($loopback, $matchClients, true)) {
                    array_unshift($matchClients, $loopback);
                }
            }

            foreach ([
                'match-clients'  => $matchClients,
                'allow-query'    => $view->getAllowQuery(),
                'allow-transfer' => $view->getAllowTransfer(),
                'also-notify'    => $view->getAlsoNotify(),
            ] as $directive => $entries) {
                if (!empty($entries)) {
                    $lines[] = '    ' . $directive . ' { ' . implode('; ', $entries) . '; };';
                }
            }

            if ($view->getExtraOptions()) {
                foreach (explode("\n", rtrim($view->getExtraOptions())) as $optLine) {
                    $lines[] = '    ' . $optLine;
                }
            }

            if (!empty($domains) || !empty($subnets)) {
                $lines[] = '';
            }

            $keyDirBase = $server->getKeyDirectory() ? rtrim($server->getKeyDirectory(), '/') : null;

            $isSecondary = $server->isSecondary();
            $primaryHost = $server->getPrimaryHostname();

            foreach ($domains as $domain) {
                $file    = $zonePath . '/' . $view->getName() . '/' . $domain->getName() . '.zone';
                $lines[] = '    zone "' . $domain->getName() . '" IN {';
                if ($isSecondary) {
                    $lines[] = '        type secondary;';
                    $lines[] = '        file "' . $file . '";';
                    if ($primaryHost) {
                        $lines[] = '        primaries { ' . $primaryHost . '; };';
                    }
                } else {
                    $lines[] = '        type master;';
                    $lines[] = '        file "' . $file . '";';
                    if ($domain->getDnssecPolicy()) {
                        $lines[] = '        dnssec-policy "' . $domain->getDnssecPolicy()->getName() . '";';
                        if ($keyDirBase) {
                            $lines[] = '        key-directory "' . $keyDirBase . '/' . $domain->getName() . '";';
                            $lines[] = '        inline-signing yes;';
                        }
                    }
                    if ($domain->isDdnsEnabled()
                        && $domain->getDdnsDnsServer()?->getId() === $server->getId()
                        && $server->getDdnsAlgorithm()
                    ) {
                        $lines[] = '        allow-update { key "' . $server->getDdnsKeyName() . '"; };';
                    }
                }
                $lines[] = '    };';
            }

            foreach ($subnets as $subnet) {
                foreach (array_filter([$subnet->getIpv4Cidr(), $subnet->getIpv6Cidr()]) as $cidr) {
                    $zoneName = $this->reverseZoneName($cidr);
                    $file     = $zonePath . '/' . $view->getName() . '/' . $zoneName . '.zone';
                    $lines[] = '    zone "' . $zoneName . '" IN {';
                    if ($isSecondary) {
                        $lines[] = '        type secondary;';
                        $lines[] = '        file "' . $file . '";';
                        if ($primaryHost) {
                            $lines[] = '        primaries { ' . $primaryHost . '; };';
                        }
                    } else {
                        $lines[] = '        type master;';
                        $lines[] = '        file "' . $file . '";';
                        if ($subnet->getDnssecPolicy()) {
                            $lines[] = '        dnssec-policy "' . $subnet->getDnssecPolicy()->getName() . '";';
                            if ($keyDirBase) {
                                $lines[] = '        key-directory "' . $keyDirBase . '/' . $zoneName . '";';
                                $lines[] = '        inline-signing yes;';
                            }
                        }
                        if ($subnet->isDdnsEnabled()
                            && $subnet->getDdnsDnsServer()?->getId() === $server->getId()
                            && $server->getDdnsAlgorithm()
                        ) {
                            $lines[] = '        allow-update { key "' . $server->getDdnsKeyName() . '"; };';
                        }
                    }
                    $lines[] = '    };';
                }
            }

            $lines[] = '};';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Builds an nsupdate script that replaces the SOA and NS apex records for a forward zone.
     * Used to propagate SOA/NS changes to dynamic zones without overwriting the zone file.
     */
    public function generateDomainApexNsUpdate(Domain $domain, ?DnsView $view = null): string
    {
        $ttl        = $domain->getSoaTtl()      ?? 3600;
        $nameserver = $this->ensureTrailingDot($domain->getSoaNameserver() ?? ('ns1.' . $domain->getName() . '.'));
        $email      = $this->emailToRname($domain->getSoaEmail() ?? ('hostmaster.' . $domain->getName() . '.'));
        $refresh    = $domain->getSoaRefresh()  ?? 3600;
        $retry      = $domain->getSoaRetry()    ?? 900;
        $expire     = $domain->getSoaExpire()   ?? 604800;
        $zone       = rtrim($domain->getName(), '.') . '.';

        return $this->buildApexNsUpdate($zone, $nameserver, $email, $ttl, $refresh, $retry, $expire, $view?->getNsUpdateSourceAddress());
    }

    /**
     * Builds an nsupdate script that replaces the SOA and NS apex records for a reverse zone.
     * Used to propagate SOA/NS changes to dynamic zones without overwriting the zone file.
     */
    public function generateSubnetApexNsUpdate(Subnet $subnet, string $cidr, ?DnsView $view = null): string
    {
        $ttl        = $subnet->getSoaTtl()      ?? 3600;
        $nameserver = $this->ensureTrailingDot($subnet->getSoaNameserver() ?? $this->defaultNs($view));
        $email      = $this->emailToRname($subnet->getSoaEmail() ?? $this->defaultEmail($view, false));
        $refresh    = $subnet->getSoaRefresh()  ?? 3600;
        $retry      = $subnet->getSoaRetry()    ?? 900;
        $expire     = $subnet->getSoaExpire()   ?? 604800;
        $zone       = $this->reverseZoneName($cidr) . '.';

        return $this->buildApexNsUpdate($zone, $nameserver, $email, $ttl, $refresh, $retry, $expire, $view?->getNsUpdateSourceAddress());
    }

    public function reverseZoneName(string $cidr): string
    {
        [$address, $prefix] = explode('/', $cidr);
        $prefix = (int)$prefix;

        return str_contains($address, ':')
            ? $this->ipv6ReverseZoneName($address, $prefix)
            : $this->ipv4ReverseZoneName($address, $prefix);
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private function ipv4ReverseZoneName(string $address, int $prefix): string
    {
        $octets = explode('.', $address);
        if ($prefix <= 8)  return $octets[0] . '.in-addr.arpa';
        if ($prefix <= 16) return $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
        if ($prefix <= 24) return $octets[2] . '.' . $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
        // RFC 2317 classless delegation for sub-/24
        return $octets[3] . '/' . $prefix . '.' . $octets[2] . '.' . $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
    }

    private function ipv6ReverseZoneName(string $address, int $prefix): string
    {
        $packed = inet_pton($address);
        if ($packed === false) {
            throw new \InvalidArgumentException("Invalid IPv6 address: {$address}");
        }
        $nibbles     = str_split(bin2hex($packed));
        $nibbleCount = max(1, (int)ceil($prefix / 4));
        return implode('.', array_reverse(array_slice($nibbles, 0, $nibbleCount))) . '.ip6.arpa';
    }

    private function ipv4PtrLabel(string $address, int $prefix): string
    {
        $octets = explode('.', $address);
        if ($prefix <= 8)  return $octets[3] . '.' . $octets[2] . '.' . $octets[1];
        if ($prefix <= 16) return $octets[3] . '.' . $octets[2];
        return $octets[3]; // /24 and sub-/24 (RFC 2317)
    }

    private function ipv6PtrLabel(string $address, int $prefix): string
    {
        $packed = inet_pton($address);
        if ($packed === false) {
            throw new \InvalidArgumentException("Invalid IPv6 address: {$address}");
        }
        $nibbles     = str_split(bin2hex($packed));
        $nibbleCount = (int)ceil($prefix / 4);
        return implode('.', array_reverse(array_slice($nibbles, $nibbleCount)));
    }

    private function ptrHostname(NetworkInterface $iface, ?DnsView $view, bool $isIpv6 = false): ?string
    {
        $canonicalType = $isIpv6 ? RecordType::AAAA : RecordType::A;
        foreach ($iface->getDomainRecords() as $record) {
            if (!$record->isCanonical()) {
                continue;
            }
            if ($record->getType() !== $canonicalType) {
                continue;
            }
            if (!$record->getDomain()) {
                continue;
            }
            if ($view !== null && !$this->inView($view, $record->getViews()->toArray())) {
                continue;
            }
            return $record->getFullyQualifiedHostname() . '.';
        }
        return null;
    }

    private function defaultNs(?DnsView $view): string
    {
        if ($view) {
            $domains = $this->domainsForView($view);
            foreach ($domains as $domain) {
                if ($domain->getSoaNameserver()) {
                    return $this->ensureTrailingDot($domain->getSoaNameserver());
                }
            }
        }
        return 'ns1.localhost.';
    }

    private function defaultEmail(?DnsView $view, bool $encode = true): string
    {
        if ($view) {
            $domains = $this->domainsForView($view);
            foreach ($domains as $domain) {
                if ($domain->getSoaEmail()) {
                    return $encode ? $this->emailToRname($domain->getSoaEmail()) : $domain->getSoaEmail();
                }
            }
        }
        return 'hostmaster.localhost.';
    }

    private function inView(?DnsView $view, array $entityViews): bool
    {
        if ($view === null) {
            return true;
        }
        foreach ($entityViews as $v) {
            if ($v->getId() === $view->getId()) {
                return true;
            }
        }
        return false;
    }

    private function ensureTrailingDot(string $s): string
    {
        return str_ends_with($s, '.') ? $s : $s . '.';
    }

    private function emailToRname(string $email): string
    {
        $rname = str_replace('@', '.', $email);
        return $this->ensureTrailingDot($rname);
    }

    private function buildApexNsUpdate(
        string $zone,
        string $nameserver,
        string $email,
        int $ttl,
        int $refresh,
        int $retry,
        int $expire,
        ?string $localAddress = null,
    ): string {
        $serial = time();
        $soa    = implode(' ', [$nameserver, $email, $serial, $refresh, $retry, $expire, $ttl]);

        $lines = [];
        if ($localAddress !== null) {
            $lines[] = 'local ' . $localAddress;
        }
        array_push($lines,
            'server 127.0.0.1',
            'zone ' . $zone,
            'update delete ' . $zone . ' IN NS',
            'update add ' . $zone . ' ' . $ttl . ' IN NS ' . $nameserver,
            'update delete ' . $zone . ' IN SOA',
            'update add ' . $zone . ' ' . $ttl . ' IN SOA ' . $soa,
            'send',
            '',
        );

        return implode("\n", $lines);
    }
}
