<?php

namespace App\Service;

use App\Entity\Domain;
use App\Entity\DnsServer;
use App\Entity\DnsView;
use App\Entity\NetworkInterface;
use App\Entity\Subnet;
use App\Repository\DomainRepository;
use App\Repository\SubnetRepository;

class DnsConfigGenerator
{
    public function __construct(
        private readonly DomainRepository $domainRepo,
        private readonly SubnetRepository $subnetRepo,
    ) {}

    /** @return Domain[] */
    public function domainsForView(DnsView $view): array
    {
        return $this->domainRepo->createQueryBuilder('d')
            ->join('d.views', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $view->getId())
            ->orderBy('d.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /** @return Subnet[] */
    public function subnetsForView(DnsView $view): array
    {
        return $this->subnetRepo->createQueryBuilder('s')
            ->join('s.views', 'v')
            ->where('v.id = :id')
            ->setParameter('id', $view->getId())
            ->orderBy('s.name', 'ASC')
            ->getQuery()
            ->getResult();
    }

    /**
     * Generates a BIND forward zone file for a domain, filtered to a specific view.
     * Pass null to include all records regardless of view.
     */
    public function generateZoneFile(Domain $domain, ?DnsView $view = null): string
    {
        $defaultTtl = $domain->getSoaTtl() ?? 3600;
        $serial     = time();
        $nameserver = $this->ensureTrailingDot($domain->getSoaNameserver() ?? ('ns1.' . $domain->getName() . '.'));
        $email      = $this->emailToRname($domain->getSoaEmail() ?? ('hostmaster.' . $domain->getName() . '.'));
        $refresh    = $domain->getSoaRefresh() ?? 3600;
        $retry      = $domain->getSoaRetry()   ?? 900;
        $expire     = $domain->getSoaExpire()  ?? 604800;

        $lines   = [];
        $lines[] = '; Zone file for ' . $domain->getName() . ($view ? ' (view: ' . $view->getName() . ')' : '');
        $lines[] = '; Generated by IPAM at ' . date('Y-m-d H:i:s T');
        $lines[] = '';
        $lines[] = '$ORIGIN ' . rtrim($domain->getName(), '.') . '.';
        $lines[] = '$TTL ' . $defaultTtl;
        $lines[] = '';
        $lines[] = sprintf(
            "@ IN SOA %s %s (\n    %-12s ; serial\n    %-12s ; refresh\n    %-12s ; retry\n    %-12s ; expire\n    %-12s ; minimum TTL\n)",
            $nameserver, $email, $serial, $refresh, $retry, $expire, $defaultTtl
        );
        $lines[] = '';
        $lines[] = sprintf('@ IN NS %s', $nameserver);
        $lines[] = '';

        // A/AAAA from interface names
        $ifaceLines = [];
        foreach ($domain->getInterfaceNames() as $ifaceName) {
            if (!$this->inView($view, $ifaceName->getViews()->toArray())) {
                continue;
            }
            $iface = $ifaceName->getNetworkInterface();
            if (!$iface) {
                continue;
            }
            $label = $ifaceName->getName();
            $ttl   = $ifaceName->getTtl() ? (' ' . $ifaceName->getTtl()) : '';
            if ($iface->getIpAddress()) {
                $ifaceLines[] = sprintf('%s%s IN A %s', $label, $ttl, $iface->getIpAddress()->getAddress());
            }
            if ($iface->getIpv6Address()) {
                $ifaceLines[] = sprintf('%s%s IN AAAA %s', $label, $ttl, $iface->getIpv6Address()->getAddress());
            }
        }
        if (!empty($ifaceLines)) {
            $lines[] = '; Interface names';
            array_push($lines, ...$ifaceLines);
            $lines[] = '';
        }

        // Manual records
        $recordLines = [];
        foreach ($domain->getRecords() as $record) {
            if (!$this->inView($view, $record->getViews()->toArray())) {
                continue;
            }
            $ttl           = $record->getTtl() ? (' ' . $record->getTtl()) : '';
            $recordLines[] = sprintf('%s%s IN %s %s', $record->getHostname(), $ttl, $record->getType()->value, $record->getValue());
        }
        if (!empty($recordLines)) {
            $lines[] = '; Manual records';
            array_push($lines, ...$recordLines);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Generates a BIND reverse zone file for a subnet CIDR (IPv4 or IPv6).
     * PTR records are derived from interface DNS names filtered to the given view.
     */
    public function generateReverseZoneFile(Subnet $subnet, string $cidr, ?DnsView $view = null): string
    {
        [$address, $prefixStr] = explode('/', $cidr);
        $prefix  = (int)$prefixStr;
        $isIpv6  = str_contains($address, ':');
        $zoneName = $this->reverseZoneName($cidr);

        $nameserver = $this->ensureTrailingDot($subnet->getSoaNameserver() ?? $this->defaultNs($view));
        $email      = $this->emailToRname($subnet->getSoaEmail() ?? $this->defaultEmail($view, false));
        $defaultTtl = $subnet->getSoaTtl()    ?? 3600;
        $refresh    = $subnet->getSoaRefresh() ?? 3600;
        $retry      = $subnet->getSoaRetry()   ?? 900;
        $expire     = $subnet->getSoaExpire()  ?? 604800;
        $serial     = time();

        $lines   = [];
        $lines[] = '; Reverse zone for ' . $cidr . ($view ? ' (view: ' . $view->getName() . ')' : '');
        $lines[] = '; Generated by IPAM at ' . date('Y-m-d H:i:s T');
        $lines[] = '';
        $lines[] = '$ORIGIN ' . $zoneName . '.';
        $lines[] = '$TTL ' . $defaultTtl;
        $lines[] = '';
        $lines[] = sprintf(
            "@ IN SOA %s %s (\n    %-12s ; serial\n    %-12s ; refresh\n    %-12s ; retry\n    %-12s ; expire\n    %-12s ; minimum TTL\n)",
            $nameserver, $email, $serial, $refresh, $retry, $expire, $defaultTtl
        );
        $lines[] = '';
        $lines[] = sprintf('@ IN NS %s', $nameserver);
        $lines[] = '';

        $ptrLines = [];
        foreach ($subnet->getInterfaces() as $iface) {
            $ip = $isIpv6 ? $iface->getIpv6Address() : $iface->getIpAddress();
            if (!$ip) {
                continue;
            }

            $hostname = $this->ptrHostname($iface, $view);
            if (!$hostname) {
                continue;
            }

            $label      = $isIpv6
                ? $this->ipv6PtrLabel($ip->getAddress(), $prefix)
                : $this->ipv4PtrLabel($ip->getAddress(), $prefix);
            $ptrLines[] = sprintf('%s IN PTR %s', $label, $hostname);
        }

        if (!empty($ptrLines)) {
            array_push($lines, ...$ptrLines);
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * Generates a views.conf BIND include file listing all forward and reverse zones.
     */
    public function generateViewsConf(DnsServer $server): string
    {
        $zonePath = rtrim($server->getRemoteZonePath(), '/');

        $lines   = [];
        $lines[] = '// BIND views configuration — generated by IPAM at ' . date('Y-m-d H:i:s T');
        $lines[] = '// Include in named.conf:  include "' . $zonePath . '/views.conf";';
        $lines[] = '';

        foreach ($server->getViews() as $view) {
            $domains = $this->domainsForView($view);
            $subnets = $this->subnetsForView($view);

            $lines[] = 'view "' . $view->getName() . '" {';

            foreach ($domains as $domain) {
                $file    = $zonePath . '/' . $view->getName() . '/' . $domain->getName() . '.zone';
                $lines[] = '    zone "' . $domain->getName() . '" IN {';
                $lines[] = '        type master;';
                $lines[] = '        file "' . $file . '";';
                $lines[] = '    };';
            }

            foreach ($subnets as $subnet) {
                foreach (array_filter([$subnet->getIpv4Cidr(), $subnet->getIpv6Cidr()]) as $cidr) {
                    $zoneName = $this->reverseZoneName($cidr);
                    $file     = $zonePath . '/' . $view->getName() . '/' . $zoneName . '.zone';
                    $lines[] = '    zone "' . $zoneName . '" IN {';
                    $lines[] = '        type master;';
                    $lines[] = '        file "' . $file . '";';
                    $lines[] = '    };';
                }
            }

            $lines[] = '};';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function reverseZoneName(string $cidr): string
    {
        [$address, $prefix] = explode('/', $cidr);
        $prefix = (int)$prefix;

        return str_contains($address, ':')
            ? $this->ipv6ReverseZoneName($address, $prefix)
            : $this->ipv4ReverseZoneName($address, $prefix);
    }

    // -------------------------------------------------------------------------
    // Private helpers
    // -------------------------------------------------------------------------

    private function ipv4ReverseZoneName(string $address, int $prefix): string
    {
        $octets = explode('.', $address);
        if ($prefix <= 8)  return $octets[0] . '.in-addr.arpa';
        if ($prefix <= 16) return $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
        if ($prefix <= 24) return $octets[2] . '.' . $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
        // RFC 2317 classless delegation for sub-/24
        return $octets[3] . '/' . $prefix . '.' . $octets[2] . '.' . $octets[1] . '.' . $octets[0] . '.in-addr.arpa';
    }

    private function ipv6ReverseZoneName(string $address, int $prefix): string
    {
        $nibbles     = str_split(bin2hex(inet_pton($address)));
        $nibbleCount = (int)ceil($prefix / 4);
        return implode('.', array_reverse(array_slice($nibbles, 0, $nibbleCount))) . '.ip6.arpa';
    }

    private function ipv4PtrLabel(string $address, int $prefix): string
    {
        $octets = explode('.', $address);
        if ($prefix <= 8)  return $octets[3] . '.' . $octets[2] . '.' . $octets[1];
        if ($prefix <= 16) return $octets[3] . '.' . $octets[2];
        return $octets[3]; // /24 and sub-/24 (RFC 2317)
    }

    private function ipv6PtrLabel(string $address, int $prefix): string
    {
        $nibbles     = str_split(bin2hex(inet_pton($address)));
        $nibbleCount = (int)ceil($prefix / 4);
        return implode('.', array_reverse(array_slice($nibbles, $nibbleCount)));
    }

    private function ptrHostname(NetworkInterface $iface, ?DnsView $view): ?string
    {
        foreach ($iface->getNames() as $name) {
            if (!$name->getDomain()) {
                continue;
            }
            if ($view !== null && !$this->inView($view, $name->getViews()->toArray())) {
                continue;
            }
            return $name->getFullyQualifiedName() . '.';
        }
        return null;
    }

    private function defaultNs(?DnsView $view): string
    {
        if ($view) {
            $domains = $this->domainsForView($view);
            foreach ($domains as $domain) {
                if ($domain->getSoaNameserver()) {
                    return $this->ensureTrailingDot($domain->getSoaNameserver());
                }
            }
        }
        return 'ns1.localhost.';
    }

    private function defaultEmail(?DnsView $view, bool $encode = true): string
    {
        if ($view) {
            $domains = $this->domainsForView($view);
            foreach ($domains as $domain) {
                if ($domain->getSoaEmail()) {
                    return $encode ? $this->emailToRname($domain->getSoaEmail()) : $domain->getSoaEmail();
                }
            }
        }
        return 'hostmaster.localhost.';
    }

    private function inView(?DnsView $view, array $entityViews): bool
    {
        if ($view === null) {
            return true;
        }
        foreach ($entityViews as $v) {
            if ($v->getId() === $view->getId()) {
                return true;
            }
        }
        return false;
    }

    private function ensureTrailingDot(string $s): string
    {
        return str_ends_with($s, '.') ? $s : $s . '.';
    }

    private function emailToRname(string $email): string
    {
        $rname = str_replace('@', '.', $email);
        return $this->ensureTrailingDot($rname);
    }
}
