<?php

namespace App\Service;

use App\Repository\NetworkInterfaceRepository;
use App\Repository\RadiusClientRepository;

class RadiusConfigGenerator
{
    public function __construct(
        private readonly RadiusClientRepository    $clientRepo,
        private readonly NetworkInterfaceRepository $ifaceRepo,
    ) {}

    public function generateClientsConf(): string
    {
        $clients = $this->clientRepo->findBy(['enabled' => true], ['name' => 'ASC']);

        $lines = [];
        $lines[] = '# Generated by DashDDI — do not edit manually';
        $lines[] = '';

        foreach ($clients as $client) {
            $blockName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $client->getName());
            $lines[] = 'client ' . $blockName . ' {';
            $lines[] = '    ipaddr                        = ' . $client->getNasname();
            $lines[] = '    secret                        = ' . $client->getSecret();
            if ($client->getShortname() !== null) {
                $lines[] = '    shortname                     = ' . $client->getShortname();
            }
            $lines[] = '    require_message_authenticator = true';
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    public function generateDefaultSite(): string
    {
        return <<<'CONF'
# Generated by DashDDI — do not edit manually
server default {
    listen {
        type   = auth
        ipaddr = *
        port   = 1812
    }

    listen {
        type   = acct
        ipaddr = *
        port   = 1813
    }

    authorize {
        if (&Service-Type == Call-Check) {
            files
            if (notfound) {
                reject
            }
            return
        }
        reject
    }

    authenticate {
    }

    post-auth {
        Post-Auth-Type REJECT {
        }
    }

    accounting {
    }

    session {
    }

    pre-proxy {
    }

    post-proxy {
    }
}
CONF;
    }

    public function generateAuthorizeFile(): string
    {
        $interfaces = $this->ifaceRepo->findAllForRadiusAuth();

        $lines = ['# Generated by DashDDI — do not edit manually', ''];

        foreach ($interfaces as $iface) {
            $mac    = $iface->getMacAddress();
            $vlan   = $iface->getSubnet()?->getVlan();

            $filterId = null;
            foreach ($iface->getNames() as $name) {
                if ($name->isCanonical() && ($fqn = $name->getFullyQualifiedName()) !== null) {
                    $filterId = $fqn;
                    break;
                }
            }

            $lines[] = $mac . "\tAuth-Type := Accept";

            $replyAttrs = [];
            if ($vlan !== null) {
                $replyAttrs[] = 'Tunnel-Type = 13';
                $replyAttrs[] = 'Tunnel-Medium-Type = 6';
                $replyAttrs[] = 'Tunnel-Private-Group-ID = "' . $vlan . '"';
            }
            if ($filterId !== null) {
                $replyAttrs[] = 'Filter-Id = "' . $filterId . '"';
            }

            $last = count($replyAttrs) - 1;
            foreach ($replyAttrs as $i => $attr) {
                $lines[] = "\t" . $attr . ($i < $last ? ',' : '');
            }

            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
