<?php

namespace App\Service;

use App\Repository\NetworkInterfaceRepository;
use App\Repository\RadiusClientRepository;

class RadiusConfigGenerator
{
    public function __construct(
        private readonly RadiusClientRepository    $clientRepo,
        private readonly NetworkInterfaceRepository $ifaceRepo,
    ) {}

    public function generateClientsConf(): string
    {
        $clients = $this->clientRepo->findBy(['enabled' => true], ['name' => 'ASC']);

        $lines = [];
        $lines[] = '# Generated by DashDDI — do not edit manually';
        $lines[] = '';

        foreach ($clients as $client) {
            $blockName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $client->getName());
            $lines[] = 'client ' . $blockName . ' {';
            $lines[] = '    ipaddr                        = ' . $client->getNasname();
            $lines[] = '    secret                        = ' . $client->getSecret();
            if ($client->getShortname() !== null) {
                $lines[] = '    shortname                     = ' . $client->getShortname();
            }
            $lines[] = '    require_message_authenticator = true';
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }

    /**
     * FreeRADIUS users/authorize file.
     *
     * Each known MAC address (from network_interface) gets an Auth-Type := Accept
     * entry.  VLAN tunnel attributes are added when the interface's subnet has a
     * VLAN, and Filter-Id is set to the canonical hostname when one exists —
     * matching the behaviour of the SQL-backed authorize queries on main.
     */
    public function generateAuthorizeFile(): string
    {
        $interfaces = $this->ifaceRepo->findAllForRadiusAuth();

        $lines = ['# Generated by DashDDI — do not edit manually', ''];

        foreach ($interfaces as $iface) {
            $mac    = $iface->getMacAddress();
            $vlan   = $iface->getSubnet()?->getVlan();

            $filterId = null;
            foreach ($iface->getNames() as $name) {
                if ($name->isCanonical() && ($fqn = $name->getFullyQualifiedName()) !== null) {
                    $filterId = $fqn;
                    break;
                }
            }

            $lines[] = $mac . "\tAuth-Type := Accept";

            $replyAttrs = [];
            if ($vlan !== null) {
                $replyAttrs[] = 'Tunnel-Type = 13';
                $replyAttrs[] = 'Tunnel-Medium-Type = 6';
                $replyAttrs[] = 'Tunnel-Private-Group-ID = "' . $vlan . '"';
            }
            if ($filterId !== null) {
                $replyAttrs[] = 'Filter-Id = "' . $filterId . '"';
            }

            $last = count($replyAttrs) - 1;
            foreach ($replyAttrs as $i => $attr) {
                $lines[] = "\t" . $attr . ($i < $last ? ',' : '');
            }

            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
