<?php

namespace App\Service;

use App\Repository\RadiusClientRepository;

class RadiusConfigGenerator
{
    public function __construct(
        private readonly RadiusClientRepository $clientRepo,
    ) {}

    public function generateClientsConf(): string
    {
        $clients = $this->clientRepo->findBy(['enabled' => true], ['name' => 'ASC']);

        $lines = [];
        $lines[] = '# Generated by DashDDI — do not edit manually';
        $lines[] = '';

        foreach ($clients as $client) {
            $blockName = preg_replace('/[^a-zA-Z0-9_-]/', '_', $client->getName());
            $lines[] = 'client ' . $blockName . ' {';
            $lines[] = '    ipaddr    = ' . $client->getNasname();
            $lines[] = '    secret    = ' . $client->getSecret();
            if ($client->getShortname() !== null) {
                $lines[] = '    shortname = ' . $client->getShortname();
            }
            $lines[] = '}';
            $lines[] = '';
        }

        return implode("\n", $lines);
    }
}
