framework:
    messenger:
        transports:
            async: '%env(MESSENGER_TRANSPORT_DSN)%'
            failed: 'doctrine://default?queue_name=failed'
        failure_transport: failed

        routing:
            'App\Message\PushClearpassMessage': async
            'App\Message\PushDnsMessage': async
            'App\Message\PushDhcpMessage': async
            'App\Message\RunScheduledTaskMessage': async
            'App\Message\PullSnipeItMessage': async
