[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "certbot-dns-dashddi"
version = "2.0.0"
description = "Certbot DNS authenticator plugin for dashddi"
requires-python = ">=3.9"
dependencies = [
    "certbot>=2.0",
    "requests>=2.28",
]

[project.entry-points."certbot.plugins"]
dns-dashddi = "certbot_dns_dashddi._internal.dns_dashddi:Authenticator"

[tool.setuptools.packages.find]
include = ["certbot_dns_dashddi*"]

[project.scripts]
dashddi-certbot = "certbot_dns_dashddi._internal.renew:main"
